### PR TITLE
Jelly, web, healing potion+ covers

### PR DESCRIPTION
**Pull request by IKnewOne**
Sorry for making a lot of small requests. Just fixing things when i see them, and add asap

### CODE REVIEW

**Comment by IKnewOne** [comment]
I'm not sure about cover images because somewhere it's : or _ , but for images it's always _

**Comment by NetroScript** [comment]
Because ":" is not an accepted character in windows file system, it is replaced by 2 "_" - meaning if you want to write "seed:1" you would write "seed__1"

**Comment by IKnewOne** [comment]
Oh yeah. Makes sense

**Comment by NetroScript** [comment]
` data/html/rsc/cover__cover_hard.png` can stay, because if ` data/html/rsc/cover__cover_hard__1.png` does not exist, it checks if the item exists without quality names appended

**Comment by IKnewOne** [comment]
i'd rather make it civil, and add __ everywhere
doing it right now

**Comment by NetroScript** [comment]
Why would it be more civil then? You would have more images then which are needless files because it uses a fallback if the name doesn't exist.

**Comment by IKnewOne** [comment]
oh, you do need "cover_cover_hard" ?
alright then, gonna make the way to want it

**Comment by NetroScript** [comment]
Considering the way the item image is retrieved it would be better to just have the image without qualities, because the quality doesn't change the image itself, so you have 1 image file instead of 3. When I will add the missing item image, I will also replace all the unnecessarily item quality images by the base version (if it doesn't exist yet) - Meaning it would be better to leave `cover__cover_hard.png` in, instead of adding `cover__cover_hard__<num>.png` images.

**Comment by NetroScript** [comment]
If you change that back, I will merge this + add a commit which should fix #5 and then release 0.1.6 (after so many small changes (items, + 1 reason for an error))

**Comment by IKnewOne** [comment]
How do stars add to the item them ? Internal logic of app or what ?

**Comment by NetroScript** [comment]
Yup, the app checks for a base image of the item, then you can manipulate it's quality, this won't change the item image, but change a small image in the corner of the item and change the internal name displayed in parentheses

**Comment by IKnewOne** [comment]
It would be best if you just merge this, delete useless pngs and compile. I wont be sble to get tk my github on computer for ~10 hours or so

**Pull request merged**
